### ISSUE TITLE
Message returned is unnecessary

### ISSUE THREAD

**Issue by jackstenglein** [jamrizzi/check-params#1]
The message 'You have all of the correct params.' is implied when no error is thrown and doesn't need to be returned.

**Comment by clayrisser** [comment]
Thanks for the advice. I agree with you. I'll remove the message.

**Comment by clayrisser** [comment]
I fixed this in commit 65c5e63661793fc6aa3ace79b5dc29cf98068156

**Comment by clayrisser** [comment]
Update to the most recent version to get the update
